# 05-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: minio
spec:
  type: NodePort # Для зовнішнього доступу
  selector:
    app: minio # Пов'язує сервіс з нашим Deployment
  ports:
    - name: api
      protocol: TCP
      port: 9000
      targetPort: 9000
      # nodePort: 30090 # Можна вказати статичний порт
    - name: console
      protocol: TCP
      port: 9001
      targetPort: 9001
      # nodePort: 30091 # Можна вказати статичний порт