# ---
# 3. Сервіс (Service)
# Надає стабільний мережевий доступ до нашого поду.
# ---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
  namespace: mlflow
spec:
  # NodePort робить сервіс доступним на певному порту кожного вузла
  # в кластері. Ідеально для доступу в Minikube.
  type: NodePort
  ports:
    - port: 5000 # Внутрішній порт сервісу в кластері.
      targetPort: 5000 # Порт, на якому слухає контейнер (pod).
      # nodePort: 30007 # Можна вказати статичний порт, але краще дозволити Kubernetes обрати вільний.
  selector:
    # Сервіс направляє трафік на всі поди з міткою 'app: mlflow'.
    app: mlflow
